/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.mydsl.ide;

import fr.ut2j.m1ice.mydsl.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
