/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.mydsl.ide

import com.google.inject.Guice
import fr.ut2j.m1ice.mydsl.MyDslRuntimeModule
import fr.ut2j.m1ice.mydsl.MyDslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MyDslIdeSetup extends MyDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MyDslRuntimeModule, new MyDslIdeModule))
	}
	
}
