/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
