/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.mydsl.ui.tests;

import com.google.inject.Injector;
import fr.ut2j.m1ice.mydsl.ui.internal.MydslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("fr.ut2j.m1ice.mydsl.MyDsl");
	}

}
