/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.mydsl;

import fr.ut2j.m1ice.mydsl.AbstractMyDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
